site_name: Metaversity
site_description: 
# repo_url: "https://github.com/SciEcon/publication-website/"

theme:
  palette: 
    scheme: default
  
  
  name: material
  custom_dir: overrides
  logo: assets/logo-dark-mode-v1.png
  favicon: assets/metaversity-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate


nav:
  - Home: index.md
  - About: About.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

copyright: Copyright &copy; 2021 - 2022 SciEcon CIC, Hosted on the Internet Computer

extra_css:
  - stylesheets/extra.css